import { createClient } from 'npm:@supabase/supabase-js@2.112.2'
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'POST, OPTIONS'}
const out=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})
async function shaBlob(b:Blob){const d=await crypto.subtle.digest('SHA-256',await b.arrayBuffer());return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sniff(blob:Blob,mime:string){const a=new Uint8Array(await blob.slice(0,64).arrayBuffer()),txt=new TextDecoder('latin1').decode(a);if(mime.includes('wav'))return txt.startsWith('RIFF')&&txt.slice(8,12)==='WAVE';if(mime.includes('webm'))return a.length>=4&&a[0]===0x1a&&a[1]===0x45&&a[2]===0xdf&&a[3]===0xa3;if(mime.includes('ogg'))return txt.startsWith('OggS');if(mime.includes('mp4')||mime.includes('m4a'))return txt.slice(4,12).includes('ftyp');return false}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({ok:false,error:'method_not_allowed'},405)
 try{
  const url=Deno.env.get('SUPABASE_URL')||'',pubs=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}'),secs=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),pub=pubs.default||Deno.env.get('SUPABASE_ANON_KEY')||'',secret=secs.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',auth=req.headers.get('authorization')||'',jwt=auth.startsWith('Bearer ')?auth.slice(7):''
  if(!jwt)return out({ok:false,error:'auth_required'},401)
  const uc=createClient(url,pub,{global:{headers:{Authorization:`Bearer ${jwt}`}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}}),{data:ud}=await uc.auth.getUser(jwt),user=ud?.user
  if(!user)return out({ok:false,error:'invalid_session'},401)
  const b=await req.json().catch(()=>({})),uploadId=String(b.upload_id||''),clientSha=String(b.sha256||'').toLowerCase(),duration=Math.max(.01,Number(b.duration_seconds||0)),sampleRate=Number(b.sample_rate||0)||null,channels=Number(b.channels||0)||null
  if(!/^[0-9a-f-]{36}$/i.test(uploadId)||!/^[0-9a-f]{64}$/i.test(clientSha))return out({ok:false,error:'invalid_finalize_request'},400)
  if(!Number.isFinite(duration)||duration>21600)return out({ok:false,error:'invalid_duration'},400)
  const {data:up}=await admin.from('recording_uploads').select('*').eq('id',uploadId).eq('user_id',user.id).maybeSingle();if(!up)return out({ok:false,error:'upload_not_found'},404)
  if(up.finalized_at)return out({ok:true,already_finalized:true,asset_id:up.asset_id,take_id:up.take_id,track_id:up.track_id})
  if(Date.parse(up.expires_at)<Date.now())return out({ok:false,error:'upload_expired'},410)
  const sourceType=String(up.metadata?.source_type||'recording');if(!['recording','instrument_render','video_audio_render','source_import'].includes(sourceType))return out({ok:false,error:'invalid_upload_source_type'},409)
  const {data:blob,error:de}=await admin.storage.from(up.storage_bucket).download(up.storage_path);if(de||!blob)return out({ok:false,error:'uploaded_recording_missing'},409)
  if(blob.size<44||blob.size>96*1024*1024)return out({ok:false,error:'uploaded_recording_size_invalid'},400)
  const actualSha=await shaBlob(blob);if(actualSha!==clientSha)return out({ok:false,error:'recording_sha256_mismatch'},409)
  if(!await sniff(blob,up.mime_type))return out({ok:false,error:'recording_signature_invalid'},415)
  const {data:obj}=await admin.schema('storage').from('objects').select('metadata').eq('bucket_id',up.storage_bucket).eq('name',up.storage_path).maybeSingle(),storedMime=String(obj?.metadata?.mimetype||up.mime_type)
  const {data:maxT}=await admin.from('tracks').select('position').eq('project_id',up.project_id).eq('user_id',user.id).order('position',{ascending:false}).limit(1).maybeSingle(),position=Number(maxT?.position??-1)+1,trackId=crypto.randomUUID(),clipId=crypto.randomUUID()
  if(sourceType==='source_import'){
   const trackName=String(up.metadata?.track_name||`Importado · ${up.original_name||'Áudio'}`).slice(0,120),track={id:trackId,project_id:up.project_id,version_id:up.version_id,user_id:user.id,name:trackName,kind:'source',position,gain_db:0,pan:0,muted:false,solo:false,color:'#9b7cff'},asset={id:up.asset_id,project_id:up.project_id,version_id:up.version_id,user_id:user.id,kind:'source',storage_bucket:up.storage_bucket,storage_path:up.storage_path,original_name:up.original_name,mime_type:up.mime_type,size_bytes:blob.size,duration_seconds:duration,sample_rate:sampleRate,channels,sha256:actualSha,metadata:{source:'FileImport',verified_sha256:true,signature_verified:true,storage_mime:storedMime,imported_source:true}},clip={id:clipId,track_id:trackId,asset_id:up.asset_id,user_id:user.id,source_start:0,source_end:duration,timeline_start:Number(up.timeline_start||0),duration,gain_db:0,pan:0,fade_in:0,fade_out:0,playback_rate:1,pitch_shift:0,muted:false}
   const {error:ae}=await admin.from('audio_assets').insert(asset);if(ae)throw ae
   const {error:te}=await admin.from('tracks').insert(track);if(te){await admin.from('audio_assets').delete().eq('id',up.asset_id);throw te}
   const {error:ce}=await admin.from('clips').insert(clip);if(ce){await admin.from('tracks').delete().eq('id',trackId);await admin.from('audio_assets').delete().eq('id',up.asset_id);throw ce}
   await admin.from('studio_actions').insert({project_id:up.project_id,user_id:user.id,action_type:'import_source',target_type:'asset',target_id:up.asset_id,before_state:{},after_state:{track,clip,asset:{id:asset.id}},status:'applied'})
   await admin.from('recording_uploads').update({track_id:trackId,finalized_at:new Date().toISOString(),metadata:{...(up.metadata||{}),actual_size:blob.size,sha256:actualSha,duration_seconds:duration,sample_rate:sampleRate,channels}}).eq('id',uploadId)
   return out({ok:true,source_type:sourceType,asset_id:up.asset_id,track_id:trackId,clip_id:clipId,size_bytes:blob.size,sha256:actualSha,duration_seconds:duration,sample_rate:sampleRate,channels})
  }
  if(sourceType==='instrument_render'||sourceType==='video_audio_render'){
   const isVideo=sourceType==='video_audio_render',trackName=String(up.metadata?.track_name||(isVideo?'Áudio tratado do vídeo':'Instrument Lab')).slice(0,120),track={id:trackId,project_id:up.project_id,version_id:up.version_id,user_id:user.id,name:trackName,kind:isVideo?'video_audio':'instrument',position,gain_db:0,pan:0,muted:false,solo:false,color:isVideo?'#54c7ec':'#9b7cff'}
   const metadata:any={source:isVideo?'MediaElementAudioSourceNode+MediaRecorder':'OfflineAudioContext',verified_sha256:true,signature_verified:true,storage_mime:storedMime}
   if(isVideo)Object.assign(metadata,{profile:String(up.metadata?.profile||'voice_clear'),source_video_name:up.metadata?.source_video_name||null,source_video_type:up.metadata?.source_video_type||null,source_video_size:up.metadata?.source_video_size||null})
   else Object.assign(metadata,{preset:String(up.metadata?.preset||'warm_keys'),bpm:Number(up.metadata?.bpm||0)||null})
   const asset={id:up.asset_id,project_id:up.project_id,version_id:up.version_id,user_id:user.id,kind:isVideo?'video_audio_render':'instrument_render',storage_bucket:up.storage_bucket,storage_path:up.storage_path,original_name:up.original_name,mime_type:up.mime_type,size_bytes:blob.size,duration_seconds:duration,sample_rate:sampleRate,channels,bit_depth:isVideo?null:16,sha256:actualSha,metadata}
   const clip={id:clipId,track_id:trackId,asset_id:up.asset_id,user_id:user.id,source_start:0,source_end:duration,timeline_start:Number(up.timeline_start||0),duration,gain_db:0,pan:0,fade_in:0,fade_out:0,playback_rate:1,pitch_shift:0,muted:false}
   const {error:ae}=await admin.from('audio_assets').insert(asset);if(ae)throw ae
   const {error:te}=await admin.from('tracks').insert(track);if(te){await admin.from('audio_assets').delete().eq('id',up.asset_id);throw te}
   const {error:ce}=await admin.from('clips').insert(clip);if(ce){await admin.from('tracks').delete().eq('id',trackId);await admin.from('audio_assets').delete().eq('id',up.asset_id);throw ce}
   await admin.from('studio_actions').insert({project_id:up.project_id,user_id:user.id,action_type:isVideo?'render_video_audio':'render_instrument',target_type:'asset',target_id:up.asset_id,before_state:{},after_state:{track,clip,asset:{id:asset.id}},status:'applied'})
   await admin.from('recording_uploads').update({track_id:trackId,finalized_at:new Date().toISOString(),metadata:{...(up.metadata||{}),actual_size:blob.size,sha256:actualSha,duration_seconds:duration,sample_rate:sampleRate,channels}}).eq('id',uploadId)
   return out({ok:true,source_type:sourceType,asset_id:up.asset_id,track_id:trackId,clip_id:clipId,size_bytes:blob.size,sha256:actualSha,duration_seconds:duration,sample_rate:sampleRate,channels})
  }
  const {data:maxTake}=await admin.from('takes').select('take_number').eq('project_id',up.project_id).eq('user_id',user.id).order('take_number',{ascending:false}).limit(1).maybeSingle(),takeNumber=Number(maxTake?.take_number||0)+1
  const track={id:trackId,project_id:up.project_id,version_id:up.version_id,user_id:user.id,name:`Take ${takeNumber}`,kind:'recording',position,gain_db:0,pan:0,muted:false,solo:false,color:'#ff6aa8'},asset={id:up.asset_id,project_id:up.project_id,version_id:up.version_id,user_id:user.id,kind:'take',storage_bucket:up.storage_bucket,storage_path:up.storage_path,original_name:up.original_name,mime_type:up.mime_type,size_bytes:blob.size,duration_seconds:duration,sample_rate:sampleRate,channels,sha256:actualSha,metadata:{source:'MediaRecorder',take_number:takeNumber,verified_sha256:true,signature_verified:true,storage_mime:storedMime}},take={id:up.take_id,project_id:up.project_id,track_id:trackId,asset_id:up.asset_id,user_id:user.id,take_number:takeNumber,selected:true},clip={id:clipId,track_id:trackId,asset_id:up.asset_id,user_id:user.id,source_start:0,source_end:duration,timeline_start:Number(up.timeline_start||0),duration,gain_db:0,pan:0,fade_in:0,fade_out:0,playback_rate:1,pitch_shift:0,muted:false}
  const {error:ae}=await admin.from('audio_assets').insert(asset);if(ae)throw ae;const {error:te}=await admin.from('tracks').insert(track);if(te){await admin.from('audio_assets').delete().eq('id',up.asset_id);throw te}const {error:takeE}=await admin.from('takes').insert(take);if(takeE){await admin.from('tracks').delete().eq('id',trackId);await admin.from('audio_assets').delete().eq('id',up.asset_id);throw takeE}const {error:ce}=await admin.from('clips').insert(clip);if(ce){await admin.from('takes').delete().eq('id',up.take_id);await admin.from('tracks').delete().eq('id',trackId);await admin.from('audio_assets').delete().eq('id',up.asset_id);throw ce}
  await admin.from('studio_actions').insert({project_id:up.project_id,user_id:user.id,action_type:'record_take',target_type:'take',target_id:up.take_id,before_state:{},after_state:{track,clip,take,asset:{id:asset.id}},status:'applied'});await admin.from('recording_uploads').update({track_id:trackId,finalized_at:new Date().toISOString(),metadata:{...(up.metadata||{}),actual_size:blob.size,sha256:actualSha,duration_seconds:duration}}).eq('id',uploadId)
  return out({ok:true,source_type:'recording',asset_id:up.asset_id,take_id:up.take_id,track_id:trackId,clip_id:clipId,take_number:takeNumber,size_bytes:blob.size,sha256:actualSha,duration_seconds:duration})
 }catch(e){return out({ok:false,error:String(e instanceof Error?e.message:e).slice(0,1400)},500)}
})