import { createClient } from 'npm:@supabase/supabase-js@2.112.2'
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'POST, OPTIONS'}
const out=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})
const num=(v:any,min:number,max:number)=>{const n=Number(v);if(!Number.isFinite(n))throw new Error('invalid_number');return Math.max(min,Math.min(max,n))}
const trackFields=(s:any)=>({name:s.name,kind:s.kind,position:s.position,gain_db:s.gain_db,pan:s.pan,muted:s.muted,solo:s.solo,color:s.color,version_id:s.version_id})
const clipFields=(s:any)=>({track_id:s.track_id,asset_id:s.asset_id,source_start:s.source_start,source_end:s.source_end,timeline_start:s.timeline_start,duration:s.duration,gain_db:s.gain_db,pan:s.pan,fade_in:s.fade_in,fade_out:s.fade_out,playback_rate:s.playback_rate,pitch_shift:s.pitch_shift,muted:s.muted})
const moduleNames=new Set(['instrument_lab','midi','podcast','video_audio'])
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({ok:false,error:'method_not_allowed'},405);try{const url=Deno.env.get('SUPABASE_URL')||'',pubs=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}'),secs=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}'),pub=pubs.default||Deno.env.get('SUPABASE_ANON_KEY')||'',secret=secs.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',auth=req.headers.get('authorization')||'',jwt=auth.startsWith('Bearer ')?auth.slice(7):'';if(!jwt)return out({ok:false,error:'auth_required'},401);const uc=createClient(url,pub,{global:{headers:{Authorization:`Bearer ${jwt}`}},auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const {data:ud}=await uc.auth.getUser(jwt),user=ud?.user;if(!user)return out({ok:false,error:'invalid_session'},401);const b=await req.json().catch(()=>({})),action=String(b.action||'');
async function record(projectId:string,type:string,targetType:string,targetId:string|null,before:any,after:any){const {data,error}=await admin.from('studio_actions').insert({project_id:projectId,user_id:user.id,action_type:type,target_type:targetType,target_id:targetId,before_state:before||{},after_state:after||{},status:'applied'}).select('id,created_at').maybeSingle();if(error)throw error;return data}
async function ownedTrack(id:string){const {data}=await admin.from('tracks').select('*').eq('id',id).eq('user_id',user.id).maybeSingle();return data}
async function ownedClip(id:string){const {data:c}=await admin.from('clips').select('*').eq('id',id).eq('user_id',user.id).maybeSingle();if(!c)return null;const t=await ownedTrack(c.track_id);return t?{clip:c,track:t}:null}
async function ownedProject(id:string){const {data}=await admin.from('projects').select('id,title,metadata,updated_at').eq('id',id).eq('user_id',user.id).maybeSingle();return data}
if(action==='history'){const projectId=String(b.project_id||'');const {data,error}=await admin.from('studio_actions').select('id,action_type,target_type,target_id,before_state,after_state,status,created_at,undone_at').eq('project_id',projectId).eq('user_id',user.id).neq('status','superseded').order('created_at',{ascending:false}).limit(40);if(error)throw error;return out({ok:true,actions:data||[]})}
if(action==='project_modules'){const projectId=String(b.project_id||''),p=await ownedProject(projectId);if(!p)return out({ok:false,error:'project_not_found'},404);return out({ok:true,project_id:projectId,modules:p.metadata?.studio_modules||{},updated_at:p.updated_at})}
if(action==='set_project_module'){const projectId=String(b.project_id||''),moduleName=String(b.module||'');if(!moduleNames.has(moduleName))return out({ok:false,error:'invalid_module'},400);const p=await ownedProject(projectId);if(!p)return out({ok:false,error:'project_not_found'},404);const value=b.value==null?null:b.value;if(value!==null&&(Array.isArray(value)||typeof value!=='object'))return out({ok:false,error:'invalid_module_value'},400);if(value!==null&&JSON.stringify(value).length>262144)return out({ok:false,error:'module_value_too_large'},413);const before={metadata:p.metadata||{}},metadata={...(p.metadata||{})},modules={...(metadata.studio_modules||{})};if(value===null)delete modules[moduleName];else modules[moduleName]=value;metadata.studio_modules=modules;const {data,error}=await admin.from('projects').update({metadata}).eq('id',projectId).eq('user_id',user.id).select('id,metadata,updated_at').maybeSingle();if(error)throw error;const after={metadata:data?.metadata||metadata},a=await record(projectId,'set_project_module','project',projectId,before,after);return out({ok:true,project:data,module:moduleName,value:value,action:a})}
if(action==='update_track'){const id=String(b.track_id||''),t=await ownedTrack(id);if(!t)return out({ok:false,error:'track_not_found'},404);const patch:any={};if('gain_db'in b)patch.gain_db=num(b.gain_db,-60,18);if('pan'in b)patch.pan=num(b.pan,-1,1);if('muted'in b)patch.muted=!!b.muted;if('solo'in b)patch.solo=!!b.solo;if('name'in b)patch.name=String(b.name||'').slice(0,120)||t.name;const {data,error}=await admin.from('tracks').update(patch).eq('id',id).eq('user_id',user.id).select('*').maybeSingle();if(error)throw error;const a=await record(t.project_id,'update_track','track',id,t,data);return out({ok:true,track:data,action:a})}
if(action==='update_clip'){const id=String(b.clip_id||''),o=await ownedClip(id);if(!o)return out({ok:false,error:'clip_not_found'},404);const c=o.clip,patch:any={};if('timeline_start'in b)patch.timeline_start=num(b.timeline_start,0,86400);if('source_start'in b)patch.source_start=num(b.source_start,0,86400);if('source_end'in b)patch.source_end=b.source_end==null?null:num(b.source_end,0,86400);if('duration'in b)patch.duration=num(b.duration,0.01,86400);if('gain_db'in b)patch.gain_db=num(b.gain_db,-60,18);if('pan'in b)patch.pan=num(b.pan,-1,1);if('fade_in'in b)patch.fade_in=num(b.fade_in,0,600);if('fade_out'in b)patch.fade_out=num(b.fade_out,0,600);if('playback_rate'in b)patch.playback_rate=num(b.playback_rate,0.25,4);if('pitch_shift'in b)patch.pitch_shift=num(b.pitch_shift,-24,24);if('muted'in b)patch.muted=!!b.muted;const {data,error}=await admin.from('clips').update(patch).eq('id',id).eq('user_id',user.id).select('*').maybeSingle();if(error)throw error;const a=await record(o.track.project_id,'update_clip','clip',id,c,data);return out({ok:true,clip:data,action:a})}
if(action==='split_clip'){const id=String(b.clip_id||''),at=num(b.at_seconds,0,86400),o=await ownedClip(id);if(!o)return out({ok:false,error:'clip_not_found'},404);const c=o.clip,start=Number(c.timeline_start),dur=Number(c.duration),rel=at-start;if(rel<=0.05||rel>=dur-0.05)return out({ok:false,error:'split_outside_clip'},400);const base:any={...c};delete base.id;delete base.created_at;delete base.updated_at;const left={...base,duration:rel,source_end:Number(c.source_start)+rel,fade_out:0};const right={...base,timeline_start:at,source_start:Number(c.source_start)+rel,duration:dur-rel,fade_in:0};const {data:newClips,error}=await admin.from('clips').insert([left,right]).select('*');if(error)throw error;const {error:de}=await admin.from('clips').delete().eq('id',id).eq('user_id',user.id);if(de)throw de;const a=await record(o.track.project_id,'split_clip','clip',id,{clip:c},{clips:newClips});return out({ok:true,clips:newClips,action:a})}
if(action==='duplicate_clip'){const id=String(b.clip_id||''),o=await ownedClip(id);if(!o)return out({ok:false,error:'clip_not_found'},404);const copy:any={...o.clip};delete copy.id;delete copy.created_at;delete copy.updated_at;copy.timeline_start=Number(o.clip.timeline_start)+Number(o.clip.duration);const {data,error}=await admin.from('clips').insert(copy).select('*').maybeSingle();if(error)throw error;const a=await record(o.track.project_id,'duplicate_clip','clip',id,{source_clip_id:id},{clip:data});return out({ok:true,clip:data,action:a})}
if(action==='delete_clip'){const id=String(b.clip_id||''),o=await ownedClip(id);if(!o)return out({ok:false,error:'clip_not_found'},404);const {data,error}=await admin.from('clips').delete().eq('id',id).eq('user_id',user.id).select('*').maybeSingle();if(error||!data)return out({ok:false,error:'clip_delete_failed'},500);const a=await record(o.track.project_id,'delete_clip','clip',id,{clip:o.clip},{deleted:true});return out({ok:true,id,action:a})}
async function restore(a:any,dir:'undo'|'redo'){const before=a.before_state||{},after=a.after_state||{};if(a.action_type==='set_project_module'){const state=dir==='undo'?before:after;const {error}=await admin.from('projects').update({metadata:state.metadata||{}}).eq('id',a.target_id).eq('user_id',user.id);if(error)throw error;return}
if(a.action_type==='update_track'){const state=dir==='undo'?before:after;const {error}=await admin.from('tracks').update(trackFields(state)).eq('id',a.target_id).eq('user_id',user.id);if(error)throw error;return}
if(a.action_type==='update_clip'){const state=dir==='undo'?before:after;const {error}=await admin.from('clips').update(clipFields(state)).eq('id',a.target_id).eq('user_id',user.id);if(error)throw error;return}
if(a.action_type==='split_clip'){const original=before.clip,newClips=after.clips||[];if(dir==='undo'){const ids=newClips.map((x:any)=>x.id).filter(Boolean);if(ids.length)await admin.from('clips').delete().in('id',ids).eq('user_id',user.id);const {error}=await admin.from('clips').upsert(original);if(error)throw error}else{await admin.from('clips').delete().eq('id',original.id).eq('user_id',user.id);const {error}=await admin.from('clips').upsert(newClips);if(error)throw error}return}
if(a.action_type==='duplicate_clip'){const c=after.clip;if(dir==='undo'){await admin.from('clips').delete().eq('id',c.id).eq('user_id',user.id)}else{const {error}=await admin.from('clips').upsert(c);if(error)throw error}return}
if(a.action_type==='delete_clip'){const c=before.clip;if(dir==='undo'){const {error}=await admin.from('clips').upsert(c);if(error)throw error}else{await admin.from('clips').delete().eq('id',c.id).eq('user_id',user.id)}return}
throw new Error('unsupported_history_action')}
if(action==='undo'){const projectId=String(b.project_id||'');const {data:a}=await admin.from('studio_actions').select('*').eq('project_id',projectId).eq('user_id',user.id).eq('status','applied').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!a)return out({ok:true,changed:false});await restore(a,'undo');await admin.from('studio_actions').update({status:'undone',undone_at:new Date().toISOString()}).eq('id',a.id).eq('user_id',user.id);return out({ok:true,changed:true,action_id:a.id,action_type:a.action_type})}
if(action==='redo'){const projectId=String(b.project_id||'');const {data:a}=await admin.from('studio_actions').select('*').eq('project_id',projectId).eq('user_id',user.id).eq('status','undone').order('created_at',{ascending:true}).limit(1).maybeSingle();if(!a)return out({ok:true,changed:false});await restore(a,'redo');await admin.from('studio_actions').update({status:'applied',undone_at:null}).eq('id',a.id).eq('user_id',user.id);return out({ok:true,changed:true,action_id:a.id,action_type:a.action_type})}
return out({ok:false,error:'unsupported_action'},400)}catch(e){return out({ok:false,error:String(e instanceof Error?e.message:e).slice(0,1200)},500)}})